{% set name = "folium" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/folium-{{ version }}.tar.gz
  sha256: 3cbe07e5782cbd312df99bfc9feb99f07a04d69d703557d168219e41a914ddbe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=41.2
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - branca >=0.6.0
    - jinja2 >=2.9
    - numpy
    - requests
    - xyzservices

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT
  license_file: LICENSE.txt
  summary: Make beautiful maps with Leaflet.js and Python

extra:
  recipe-maintainers:
    - ocefpaf
    - BibMartin
