{% set name = "folium" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/folium-{{ version }}.tar.gz
  sha256: 1be7dbd4a59c7d096194b5e9868402d637f99daaaa0673381deb5d407dc552ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - setuptools >=41.2
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - branca >=0.7.0
    - jinja2 >=2.9
    - numpy
    - requests

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT
  license_file: LICENSE.txt
  summary: Make beautiful maps with Leaflet.js and Python

extra:
  recipe-maintainers:
    - ocefpaf
    - BibMartin
