{% set version = "0.10.1" %}

package:
  name: folium
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/folium/folium-{{ version }}.tar.gz
  sha256: edbf79d04345a75f8503fe6d071179806ee7e3baf81ae4f329b9f3ce8f118c3d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - branca
    - jinja2
    - numpy
    - pandas
    - vincent
    - requests

test:
  imports:
    - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT
  license_file: LICENSE.txt
  summary: 'Make beautiful maps with Leaflet.js and Python'

extra:
  recipe-maintainers:
    - ocefpaf
    - BibMartin
